#!/bin/zsh


alias rcp='rsync -rgoP'

# fucking gpg
# alias gpg=gpg2 --homedir "$XDG_CONFIG_HOME"/gnupg

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert\s*$//'\'')"'
alias cowfortune='fortune | cowsay'

man() { env man $@ 2>/dev/null || /usr/bin/man $@ }

nsk() {
  mkdir .gcroots
  if [[ -f shell.nix ]]; then
    nix-instantiate shell.nix --indirect --add-root $(pwd)/.gcroots/shell.drv
    nix-shell $(readlink $(pwd)/.gcroots/shell.drv) "$@"
  elif [[ -f default.nix ]]; then
    nix-instantiate default.nix --indirect --add-root $(pwd)/.gcroots/default.drv
    nix-shell $(readlink $(pwd)/.gcroots/default.drv) "$@"
  fi
}

if exists swaymsg; then
  function workspace() {
    sleep 0.05 && swaymsg workspace $1
  }
fi

if non_gui; then
  alias edit="emacsclient -t"
  #sedit() { emacsclient -te $(for f in "$@"; do echo "(find-file-root \"${${f:A}//\"/\\\"})\""; done) }
  sedit() { emacsclient -te "(find-file-root \"${${1:A}//\"/\\\"}\")" }
elif exists swaymsg; then
  edit() { emacsclient -n "$@"; workspace 2 }
  #sedit() { emacsclient -ne $(for f in "$@"; do echo "(find-file-root \"${${f:A}//\"/\\\"}\")"; done) }
  sedit() { emacsclient -ne "(find-file-root \"${${1:A}//\"/\\\"}\")"; workspace 2 }
else
  edit() { emacsclient -n "$@" }
  sedit() { emacsclient -ne "(find-file-root \"${${1:A}//\"/\\\"}\")" }
fi

if exists gist; then
  up() {
    local MIME
    while [[ $# > 0 ]]; do
      MIME=$(file -b --mime-type "$1")
      if [[ $MIME =~ "^text/" ]]; then # gist
        if [[ -z $OUT ]]; then
          OUT="$(gist "$1")"
        else
          OUT="${OUT}\n$(gist "$1")"
        fi
        #else # upload to satori
      fi
      shift
    done
    echo $OUT | xclip -selection clipboard
    echo $OUT
  }
fi
