#!/bin/zsh

if [ -z $_SAUYON_CONF_RUN ]; then
_SAUYON_CONF_RUN=true

# Oh My Zsh config -------------------------------------------------------------
ZSH=/usr/share/oh-my-zsh
if [[ ! -d $ZSH ]]; then
	ZSH=~/.oh-my-zsh
else
	DISABLE_AUTO_UPDATE="true"
fi

ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"

plugins=(git github golang sudo cargo adb)

include $ZSH/oh-my-zsh.sh

# User configuration -----------------------------------------------------------

## Environment variables -------------------------------------------------------

export ANDROID_HOME=/opt/android-sdk

# make go work :D
export GOPATH=$HOME/devel/go

# PATH is path. DAMMIT OHMYZSH AGAIN GR
PATH=$PATH:/usr/local/heroku/bin:~/.gem/ruby/2.1.0/bin:$GOPATH/bin
[[ $platform == 'osx' ]] && PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:$PATH
PATH=$PATH:$XDG_DATA_HOME/cargo/bin
PATH=$PATH:$HOME/.local/bin
PATH=$PATH:$HOME/.local/share/cargo/bin
# to dot or not to dot?
# PATH=$PATH:.
export PATH

# LD_LIBRARY_PATH?!
LD_LIBRARY_PATH=$HOME/.rustc/rust/rustc/lib:$LD_LIBRARY_PATH

# I should really check for hidpi before doing this... (but parsing is a pita)
export GDK_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export WINIT_HIDPI_FACTOR=1

# 2 space tabs are best tabs
export PAGER="$(which less) -x2"

# Emacs ftw!
if non_gui; then
	export EDITOR='emacsclient -t'
else
	export EDITOR='emacsclient'
fi

export BROWSER="$(which firefox)"

# Environment vars for use in scripts
# I'm not actually sure this is meaningful...
export XDG_DESKTOP_DIR="$HOME/desktop"
export XDG_DOCUMENTS_DIR="$HOME/documents"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_MUSIC_DIR="$HOME/music"
export XDG_PICTURES_DIR="$HOME/images"
export XDG_PUBLICSHARE_DIR="$HOME/public"
export XDG_TEMPLATES_DIR="$HOME/.local/templates"
export XDG_VIDEOS_DIR="$HOME/videos"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"

# Unclutter home directory
export LESSHISTFILE="$XDG_DATA_HOME/less/history"
export GTK2_RC_FILES="$XDG_DATA_HOME/gtk-2.0/gtkrc"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export GNUPGHOME="$XDG_CONFIG_HOME"/gnupg
export WEECHAT_HOME="$XDG_CONFIG_HOME"/weechat
export ASPELL_CONF="per-conf $XDG_CONFIG_HOME/aspell/aspell.conf; personal $XDG_CONFIG_HOME/aspell/en.personal; repl $XDG_CONFIG_HOME/aspell/en.prepl"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgrep.conf"

export NIXPKGS="$HOME/devel/nixpkgs"
export NIX_PATH="$NIX_PATH:nixpkgs=$NIXPKGS"

#export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

# History. Yes, it's also in zshenv.
HISTFILESIZE=1000000000
HISTSIZE=100000
SAVEHIST=$HISTSIZE
HISTFILE="$XDG_DATA_HOME/zsh/history"

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# Qt5 why u no like gtk
export QT_STYLE_OVERRIDE=gtk

export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export GTK_IM_MODULE=ibus

## Misc preferences ------------------------------------------------------------------------

# Smart command-not-found with pkgfile
if exists pkgfile; then
  command_not_found_handler() {
    local pkgs cmd="$1"

    pkgs=(${(f)"$(pkgfile -b -v -- "$cmd" 2>/dev/null)"})
    if [[ -n "$pkgs" ]]; then
      printf '%s may be found in the following packages:\n' "$cmd"
      printf '  %s\n' $pkgs[@]
      return 127
    fi

	  printf 'zsh: command not found: %s\n' "$cmd"

    return 127
  }
fi

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=2

# Yay for syntax highlighting
include /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Autosuggestions!
include /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# Ok, fine, sometimes emacs is stupid. But at least it knows it.
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ '

# The greeting. Yeah, yeah, I'm unimaginative. :'(
echo "Hello, $(hostname)"'!'

fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/sauyon/downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/sauyon/downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/sauyon/downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/sauyon/downloads/google-cloud-sdk/completion.zsh.inc'; fi
