#!/bin/zsh

include() { [[ -f "$@" ]] && source "$@" }

is_ssh() { [[ -n $SSH_CONNECTION ]] || [[ -n $SSH_CLIENT ]] || [[ -n $SSH_TTY ]] }
non_gui() { is_ssh }

platform=unknown
local unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
	platform=linux
elif [[ "$unamestr" == 'Darwin' ]]; then
	platform=osx
fi
